//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllReport
    {
        public int Id { get; set; }
        public string Category { get; set; }
        public string PName { get; set; }
        public Nullable<int> SellQuantity { get; set; }
        public Nullable<int> BuyeQuantity { get; set; }
        public Nullable<int> SellPrice { get; set; }
        public Nullable<int> BuyePrice { get; set; }
        public Nullable<int> Profit { get; set; }
        public string Date { get; set; }
    }
}
