//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public int Category_Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Buying_Price { get; set; }
        public Nullable<int> Selling_price { get; set; }
        public Nullable<int> Stored { get; set; }
    
        public virtual Product_Type Product_Type { get; set; }
    }
}
